#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
apply_injuries.py
-----------------
Διαβάζει injuries.json + player-stats-2026.js,
ταιριάζει παίκτες, γράφει player_injuries.js.

Match: επώνυμο + θέση + ομάδα (με fallback επώνυμο+θέση)

Output: ../../js/data/player_injuries.js

Εκτέλεση: py apply_injuries.py
"""

import json
import re
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core.paths import DATA_RAW, APP_JS_DATA

INJ_JSON = DATA_RAW / "injuries.json"
STATS_JS = APP_JS_DATA / "player-stats-2026.js"
OUT_JS   = APP_JS_DATA / "player_injuries.js"


def load_stats(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    # Αφαίρεσε σχόλια
    lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("//")]
    text = "\n".join(lines)

    # Βρες το JSON μετά το "="
    m = re.search(r"=\s*(\{.*\})\s*;?\s*$", text, re.DOTALL)
    if not m:
        raise ValueError("δεν βρέθηκε JSON object")
    return json.loads(m.group(1))


def surname_pred(player: str) -> str:
    """'NUNN, KENDRICK' → 'NUNN'."""
    return player.split(",")[0].strip().upper()


def surname_bn(full: str) -> str:
    """'Kendrick Nunn' → 'NUNN'."""
    parts = full.strip().split()
    return parts[-1].upper() if parts else ""


def normalize(s: str) -> str:
    """Remove accents, punctuation, extra spaces."""
    s = s.upper().strip()
    s = re.sub(r"[^A-Z0-9 ]", "", s)
    s = re.sub(r"\s+", " ", s)
    return s


def main():
    print("=" * 60)
    print("APPLY INJURIES")
    print("=" * 60)

    if not INJ_JSON.exists():
        print(f"❌ Δεν βρέθηκε: {INJ_JSON}")
        return

    with open(INJ_JSON, encoding="utf-8") as f:
        inj = json.load(f)

    stats = load_stats(STATS_JS)
    print(f"Stats players:  {len(stats)}")
    print(f"Injuries:       {len(inj['players'])}")

    # Index stats: surname → list of (name_key, player_data)
    by_surname = {}
    for name_key, pdata in stats.items():
        if not isinstance(pdata, dict):
            continue
        sn = normalize(surname_pred(name_key))
        by_surname.setdefault(sn, []).append((name_key, pdata))

    matched = 0
    ambiguous = 0
    not_found = 0
    not_found_list = []
    injuries_out = {}   # name_key → injury info

    for row in inj["players"]:
        sn = normalize(surname_bn(row["player_name"]))
        pos = row["position"]
        team = row["team"]
        status = row["status"]

        candidates = by_surname.get(sn, [])
        if not candidates:
            not_found += 1
            not_found_list.append(f"{row['team']} {pos} {row['player_name']}")
            continue

        # Φιλτράρε: team + position
        match = None
        team_pos_match = [
            (k, d) for k, d in candidates
            if d.get("team") == team and d.get("position") == pos
        ]
        if len(team_pos_match) == 1:
            match = team_pos_match[0]
        elif len(team_pos_match) > 1:
            match = team_pos_match[0]
            ambiguous += 1
        else:
            # Fallback: μόνο team
            team_match = [(k, d) for k, d in candidates if d.get("team") == team]
            if len(team_match) == 1:
                match = team_match[0]
            elif len(team_match) > 1:
                match = team_match[0]
                ambiguous += 1
            else:
                # Fallback: μόνο επώνυμο (αν 1 candidate)
                if len(candidates) == 1:
                    match = candidates[0]
                else:
                    ambiguous += 1
                    match = candidates[0]

        if match is None:
            not_found += 1
            not_found_list.append(f"{row['team']} {pos} {row['player_name']}")
            continue

        name_key, _ = match
        injuries_out[name_key] = {
            "status": status,
            "status_raw": row.get("status_raw", ""),
            "round": row.get("round", ""),
            "comment": row.get("comment", ""),
            "team": team,
            "position": pos,
        }
        matched += 1

    print(f"\nMatched:     {matched}")
    print(f"Ambiguous:   {ambiguous}")
    print(f"Not found:   {not_found}")

    if not_found_list:
        print("\nΔεν βρέθηκαν:")
        for x in not_found_list[:20]:
            print(f"  {x}")
        if len(not_found_list) > 20:
            print(f"  ... και {len(not_found_list) - 20} ακόμα")

    # Γράψε JS
    js = "// Auto-generated by apply_injuries.py\n"
    js += f"// Matched: {matched} / {len(inj['players'])}\n"
    js += "window.PLAYER_INJURIES = "
    js += json.dumps(injuries_out, ensure_ascii=False, separators=(",", ":"))
    js += ";\n"

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    OUT_JS.write_text(js, encoding="utf-8")
    print(f"\n→ {OUT_JS}")

    # Preview
    out_players = [(k, v) for k, v in injuries_out.items() if v["status"] == "out"]
    print(f"\nInjured (status=out): {len(out_players)}")
    for k, v in out_players[:15]:
        print(f"  {v['team']:<4} {v['position']:<2} {k:<32} {v['round']}")


if __name__ == "__main__":
    main()