#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""convert_gamelogs_to_js.py — τελευταία 10 game logs ανά παίκτη → js/data/player-gamelogs.js"""

import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core.paths import DATA_RAW, APP_JS_DATA

OUT = APP_JS_DATA / "player-gamelogs.js"

N_KEEP = 10

def main():
    with open(DATA_RAW / "fantasy_data.json", encoding="utf-8") as f:
        fd = json.load(f)
    players = fd.get("players", fd if isinstance(fd, list) else [])

    out = {}
    for p in players:
        name = str(p.get("player", "")).strip().upper()
        if not name:
            continue
        logs = p.get("game_logs") or []
        logs = sorted(logs, key=lambda l: l.get("chrono_index", 0))[-N_KEEP:]
        out[name] = [{
            "season": l.get("season"),
            "phase":  l.get("phase"),
            "round":  l.get("round"),
            "opp":    l.get("opp_code"),
            "home":   bool(l.get("is_home")),
            "min":    l.get("min"),
            "pts":    l.get("pts"),
            "reb":    l.get("reb"),
            "ast":    l.get("ast"),
            "stl":    l.get("stl"),
            "blk":    l.get("blk"),
            "to":     l.get("to"),
            "pir":    l.get("pdk"),
            "starter":bool(l.get("starter")),
        } for l in logs]

    js = "// Auto-generated by convert_gamelogs_to_js.py\n"
    js += "window.PLAYER_GAMELOGS = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js, encoding="utf-8")
    total = sum(len(v) for v in out.values())
    print(f"OK -> {OUT}  ({OUT.stat().st_size/1024:.1f} KB, {len(out)} players, {total} rows)")

if __name__ == "__main__":
    main()