#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
convert_coaches_to_js.py
------------------------
Διαβάζει:
  ../json/coaches.json       (20 προπονητές + credits)
  ../json/coach_stats.json   (xp, wins, form, adj_avg_xp, next_opp, streak)

Γράφει:
  ../../js/data/coaches.js       → window.COACHES
  ../../js/data/coach_stats.js   → window.COACH_STATS
"""

import json
from datetime import datetime
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from core.paths import DATA_RAW, DATA_PROC, APP_JS_DATA

COACHES_JSON = DATA_RAW / "coaches.json"
STATS_JSON   = DATA_PROC / "coach_stats.json"
OUT_COACHES  = APP_JS_DATA / "coaches.js"
OUT_STATS    = APP_JS_DATA / "coach_stats.js"


def main():
    print("=" * 60)
    print("CONVERT coaches → JS")
    print("=" * 60)

    # ---- Load ----
    with open(COACHES_JSON, encoding="utf-8") as f:
        coaches_data = json.load(f)

    with open(STATS_JSON, encoding="utf-8") as f:
        stats_data = json.load(f)

    coaches   = coaches_data["coaches"]
    stats     = stats_data["coaches"]
    season    = coaches_data.get("season", 2026)
    next_round = stats_data.get("next_round")

    print(f"Coaches:      {len(coaches)}")
    print(f"Stats entries:{len(stats)}")
    print(f"Season:       {season}")
    print(f"Next round:   {next_round}")

    # ---- Merge ----
    merged = []
    for c in coaches:
        team = c["team"]
        s = stats.get(team, {})

        merged.append({
            "name":         c["name"],
            "team":         team,
            "team_full":    c["team_full"],
            "nationality":  c.get("nationality"),
            "age":          c.get("age"),
            "credits":      c.get("credits"),
            "games":        s.get("games", 0),
            "wins":         s.get("wins", 0),
            "losses":       s.get("losses", 0),
            "win_pct":      s.get("win_pct", 0.0),
            "total_xp":     s.get("total_xp", 0),
            "avg_xp":       s.get("avg_xp", 0.0),
            "form_last5":   s.get("form_last5", 0.0),
            # ΝΕΑ πεδία:
            "next_round":   s.get("next_round"),
            "next_opp":     s.get("next_opp"),
            "next_is_home": s.get("next_is_home"),
            "opp_rank":     s.get("opp_rank"),
            "streak_len":   s.get("streak_len", 0),
            "streak_type":  s.get("streak_type"),
            "streak_away":  s.get("streak_away", 0),
            "streak_factor":s.get("streak_factor", 1.0),
            "adj_avg_xp":   s.get("adj_avg_xp", 0.0),
            "history":      s.get("history", []),
        })

    # Sort by adj_avg_xp desc (για default)
    merged.sort(key=lambda x: -x["adj_avg_xp"])

    # ---- Write coaches.js ----
    js1 = "// Auto-generated by convert_coaches_to_js.py\n"
    js1 += f"// Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
    js1 += f"// Coaches: {len(merged)}\n"
    js1 += "window.COACHES = " + json.dumps(merged, ensure_ascii=False, separators=(",", ":")) + ";\n"
    OUT_COACHES.write_text(js1, encoding="utf-8")
    print(f"\n→ {OUT_COACHES}  ({OUT_COACHES.stat().st_size/1024:.1f} KB)")

    # ---- Write coach_stats.js (light version) ----
    light = {c["team"]: {
        "name":         c["name"],
        "team_full":    c["team_full"],
        "games":        c["games"],
        "wins":         c["wins"],
        "losses":       c["losses"],
        "win_pct":      c["win_pct"],
        "avg_xp":       c["avg_xp"],
        "form_last5":   c["form_last5"],
        "next_round":   c.get("next_round"),
        "next_opp":     c.get("next_opp"),
        "next_is_home": c.get("next_is_home"),
        "opp_rank":     c.get("opp_rank"),
        "streak_len":   c.get("streak_len", 0),
        "streak_type":  c.get("streak_type"),
        "streak_away":  c.get("streak_away", 0),
        "streak_factor":c.get("streak_factor", 1.0),
        "adj_avg_xp":   c.get("adj_avg_xp", 0.0),
    } for c in merged}

    js2 = "// Auto-generated by convert_coaches_to_js.py\n"
    js2 += "window.COACH_STATS = " + json.dumps(light, ensure_ascii=False, separators=(",", ":")) + ";\n"
    OUT_STATS.write_text(js2, encoding="utf-8")
    print(f"→ {OUT_STATS}  ({OUT_STATS.stat().st_size/1024:.1f} KB)")

    # ---- Preview ----
    print("\nTop 5 by adj_avg_xp:")
    for c in merged[:5]:
        ha = "H" if c.get("next_is_home") else ("A" if c.get("next_is_home") is False else "-")
        print(f"  {c['team']:<4} {c['name']:<22} cr={c['credits']}  "
              f"avg={c['avg_xp']:>6.2f}  adj={c['adj_avg_xp']:>6.2f}  "
              f"vs {c.get('next_opp') or '-':<4} ({ha})  "
              f"streak={c.get('streak_len',0)}{c.get('streak_type') or '-'}")


if __name__ == "__main__":
    main()